# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{porter2stemmer}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Neil Smith"]
  s.date = %q{2011-06-30}
  s.description = %q{This is the Porter 2 stemming algorithm, as described at 
http://snowball.tartarus.org/algorithms/english/stemmer.html It removes suffixes from English words, revealing something closer to the stem of the word. For instance "acknowledgments".stem => "acknowledg".}
  s.email = %q{neil.github@njae.me.uk}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/porter2stemmer.rb",
    "lib/porter2stemmer/constants.rb",
    "lib/porter2stemmer/implementation.rb",
    "pkg/porter2stemmer-1.0.0.gem",
    "rdoc/Porter2.html",
    "rdoc/README_rdoc.html",
    "rdoc/String.html",
    "rdoc/created.rid",
    "rdoc/index.html",
    "rdoc/lib/porter2stemmer/constants_rb.html",
    "rdoc/lib/porter2stemmer/implementation_rb.html",
    "rdoc/lib/porter2stemmer_rb.html",
    "rdoc/rdoc.css",
    "test/helper.rb",
    "test/test_porter2stemmer.rb",
    "test/test_porter2stemmer_full.rb",
    "test/test_porter2stemmer_parts.rb"
  ]
  s.homepage = %q{http://github.com/NeilNjae/porter2stemmer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A pure Ruby implementation of the Porter 2 stemmer}
  s.test_files = [
    "test/helper.rb",
    "test/test_porter2stemmer.rb",
    "test/test_porter2stemmer_full.rb",
    "test/test_porter2stemmer_parts.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

